POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "fuckoff",
    "password": "dasd",
    "email": "test@test.com"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"julle@gmail.com",
    "password":"123"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/checkLogin

### 
DELETE http://localhost:3000/logout

### 
GET http://localhost:3000/checkout/session

###

GET http://localhost:3000/get-order